import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    nav_title: "KG Solutions",
    onboarding_title: "Client Dashboard",
    onboarding_desc: "Manage your company profile and fleet.",
    connected: "Connected",
    export_report: "Export Report",
    tab_welcome: "Welcome",
    tab_company: "Company",
    tab_fleet: "Fleet",
    platform_overview: "Platform Overview",
    platform_desc: "Watch how our solution integrates with your workflow.",
    install_setup: "Installation & Setup",
    install_desc: "Step-by-step guide to installing the connector.",
    get_started: "Get Started",
    company_info: "Company Information",
    company_desc: "Please provide your company details for invoicing purposes.",
    company_name: "Company Name",
    tax_id: "Tax / VAT ID",
    billing_address: "Billing Address",
    delivery_address: "Delivery Address",
    contact_email: "Billing Email",
    phone_number: "Company Phone",
    contact_person: "Contact Person (Responsible)",
    contact_person_name: "Name",
    position: "Position",
    contact_person_email: "Direct Email",
    contact_person_phone: "Direct Phone",
    save_continue: "Save & Continue",
    car_profile: "Car Profile",
    car_desc: "Add a new vehicle to your fleet.",
    back: "Back",
    vehicle_specs: "Vehicle Specifications",
    brand: "Brand",
    model: "Model",
    engine_model: "Engine Model",
    transmission: "Transmission",
    brakes_type: "Brakes Type",
    required_photos: "Required Photos",
    photos_desc: "Please upload clear photos for verification.",
    conn_front: "Connector Front View",
    lever_side: "Lever Side View",
    ecu_part: "ECU Part Number",
    ecu_front: "ECU Front View",
    extra_photo: "Additional Photo",
    tech_docs: "Technical Documents",
    elec_scheme: "Electrical Scheme",
    elec_desc: "Upload PDF or Image of the electrical scheme",
    sensors_list: "Sensors & Actuators List",
    sensors_desc: "Upload list of sensors and actuators",
    cancel: "Cancel",
    save_car: "Save Car Profile",
    your_vehicles: "Your Vehicles",
    add_vehicle: "Add New Vehicle",
    no_vehicles: "No vehicles added yet",
    no_vehicles_desc: "Create a profile for each car to manage specific configurations and documents.",
    add_first_car: "Add Your First Car",
    configure_videos: "Configure Videos",
    demo_url: "Demo Video URL",
    setup_url: "Setup Video URL",
    save_changes: "Save Changes",
    upload_click: "Click to upload",
    uploading: "Uploading...",
    file_uploaded: "File uploaded",
    view_file: "View file",
    delete_car_confirmation: "Are you sure you want to delete this car profile?",
    docs: "Docs",
    photos: "Photos",
    logout: "Logout",
    download_zip: "Download ZIP",
    preparing_zip: "Preparing ZIP...",
    zip_ready: "ZIP Downloaded",
    download_error: "Download Failed"
  },
  es: {
    nav_title: "Soluciones KG",
    onboarding_title: "Incorporación de Clientes",
    onboarding_desc: "Complete su perfil y configure su flota.",
    connected: "Conectado",
    export_report: "Exportar Informe",
    tab_welcome: "Bienvenida",
    tab_company: "Empresa",
    tab_fleet: "Flota",
    platform_overview: "Resumen de Plataforma",
    platform_desc: "Vea cómo nuestra solución se integra con su flujo de trabajo.",
    install_setup: "Instalación y Configuración",
    install_desc: "Guía paso a paso para instalar el conector.",
    get_started: "Comenzar",
    company_info: "Información de la Empresa",
    company_desc: "Proporcione los detalles de su empresa para la facturación.",
    company_name: "Nombre de la Empresa",
    tax_id: "ID Fiscal / IVA",
    billing_address: "Dirección de Facturación",
    delivery_address: "Dirección de Entrega",
    contact_email: "Email de Facturación",
    phone_number: "Teléfono de la Empresa",
    contact_person: "Persona de Contacto (Responsable)",
    contact_person_name: "Nombre",
    position: "Cargo",
    contact_person_email: "Email Directo",
    contact_person_phone: "Teléfono Directo",
    save_continue: "Guardar y Continuar",
    car_profile: "Perfil del Vehículo",
    car_desc: "Añada un nuevo vehículo a su flota.",
    back: "Volver",
    vehicle_specs: "Especificaciones del Vehículo",
    brand: "Marca",
    model: "Modelo",
    engine_model: "Modelo de Motor",
    transmission: "Transmisión",
    brakes_type: "Tipo de Frenos",
    required_photos: "Fotos Requeridas",
    photos_desc: "Por favor suba fotos claras para verificación.",
    conn_front: "Vista Frontal Conector",
    lever_side: "Vista Lateral Palanca",
    ecu_part: "Número de Parte ECU",
    ecu_front: "Vista Frontal ECU",
    extra_photo: "Foto Adicional",
    tech_docs: "Documentos Técnicos",
    elec_scheme: "Esquema Eléctrico",
    elec_desc: "Suba PDF o Imagen del esquema eléctrico",
    sensors_list: "Lista de Sensores",
    sensors_desc: "Suba lista de sensores y actuadores",
    cancel: "Cancelar",
    save_car: "Guardar Perfil",
    your_vehicles: "Sus Vehículos",
    add_vehicle: "Añadir Vehículo",
    no_vehicles: "Aún no hay vehículos",
    no_vehicles_desc: "Cree un perfil para cada auto para gestionar configuraciones y documentos.",
    add_first_car: "Añada su Primer Auto",
    configure_videos: "Configurar Videos",
    demo_url: "URL Video Demo",
    setup_url: "URL Video Configuración",
    save_changes: "Guardar Cambios",
    upload_click: "Click para subir",
    uploading: "Subiendo...",
    file_uploaded: "Archivo subido",
    view_file: "Ver archivo",
    delete_car_confirmation: "¿Está seguro de que desea eliminar este perfil de vehículo?",
    docs: "Documentos",
    photos: "Fotos",
    logout: "Cerrar sesión",
    download_zip: "Descargar ZIP",
    preparing_zip: "Preparando ZIP...",
    zip_ready: "ZIP Descargado",
    download_error: "Error de descarga"
  },
  de: {
    nav_title: "KG Lösungen",
    onboarding_title: "Kunden-Onboarding",
    onboarding_desc: "Vervollständigen Sie Ihr Profil und richten Sie Ihre Flotte ein.",
    connected: "Verbunden",
    export_report: "Bericht Exportieren",
    tab_welcome: "Willkommen",
    tab_company: "Firma",
    tab_fleet: "Flotte",
    platform_overview: "Plattformübersicht",
    platform_desc: "Sehen Sie, wie unsere Lösung in Ihren Workflow integriert wird.",
    install_setup: "Installation & Einrichtung",
    install_desc: "Schritt-für-Schritt-Anleitung zur Installation des Steckers.",
    get_started: "Loslegen",
    company_info: "Firmeninformationen",
    company_desc: "Bitte geben Sie Ihre Firmendaten für die Rechnungsstellung an.",
    company_name: "Firmenname",
    tax_id: "Steuer-ID / USt-ID",
    billing_address: "Rechnungsadresse",
    delivery_address: "Lieferadresse",
    contact_email: "Rechnungs-E-Mail",
    phone_number: "Firmen-Telefon",
    contact_person: "Ansprechpartner (Verantwortlich)",
    contact_person_name: "Name",
    position: "Position",
    contact_person_email: "Direkte E-Mail",
    contact_person_phone: "Direkte Telefonnummer",
    save_continue: "Speichern & Weiter",
    car_profile: "Fahrzeugprofil",
    car_desc: "Fügen Sie Ihrer Flotte ein neues Fahrzeug hinzu.",
    back: "Zurück",
    vehicle_specs: "Fahrzeugspezifikationen",
    brand: "Marke",
    model: "Modell",
    engine_model: "Motormodell",
    transmission: "Getriebe",
    brakes_type: "Bremsentyp",
    required_photos: "Erforderliche Fotos",
    photos_desc: "Bitte laden Sie klare Fotos zur Überprüfung hoch.",
    conn_front: "Stecker Frontansicht",
    lever_side: "Hebel Seitenansicht",
    ecu_part: "ECU Teilenummer",
    ecu_front: "ECU Frontansicht",
    extra_photo: "Zusätzliches Foto",
    tech_docs: "Technische Dokumente",
    elec_scheme: "Schaltplan",
    elec_desc: "Laden Sie PDF oder Bild des Schaltplans hoch",
    sensors_list: "Sensorenliste",
    sensors_desc: "Laden Sie die Liste der Sensoren und Aktoren hoch",
    cancel: "Abbrechen",
    save_car: "Auto Speichern",
    your_vehicles: "Ihre Fahrzeuge",
    add_vehicle: "Fahrzeug Hinzufügen",
    no_vehicles: "Noch keine Fahrzeuge",
    no_vehicles_desc: "Erstellen Sie ein Profil für jedes Auto, um Konfigurationen zu verwalten.",
    add_first_car: "Erstes Auto Hinzufügen",
    configure_videos: "Videos Konfigurieren",
    demo_url: "Demo Video URL",
    setup_url: "Einrichtungs-Video URL",
    save_changes: "Änderungen Speichern",
    upload_click: "Klicken zum Hochladen",
    uploading: "Wird hochgeladen...",
    file_uploaded: "Datei hochgeladen",
    view_file: "Datei ansehen",
    delete_car_confirmation: "Möchten Sie dieses Fahrzeugprofil wirklich löschen?",
    docs: "Dokumente",
    photos: "Fotos",
    logout: "Abmelden",
    download_zip: "ZIP herunterladen",
    preparing_zip: "ZIP vorbereiten...",
    zip_ready: "ZIP heruntergeladen",
    download_error: "Download fehlgeschlagen"
    },
    fr: {
    nav_title: "Solutions KG",
    onboarding_title: "Intégration Client",
    onboarding_desc: "Complétez votre profil et configurez votre flotte.",
    connected: "Connecté",
    export_report: "Exporter le Rapport",
    tab_welcome: "Bienvenue",
    tab_company: "Société",
    tab_fleet: "Flotte",
    platform_overview: "Aperçu de la Plateforme",
    platform_desc: "Découvrez comment notre solution s'intègre à votre flux de travail.",
    install_setup: "Installation & Configuration",
    install_desc: "Guide étape par étape pour installer le connecteur.",
    get_started: "Commencer",
    company_info: "Informations Société",
    company_desc: "Veuillez fournir les détails de votre société pour la facturation.",
    company_name: "Nom de la Société",
    tax_id: "Numéro de TVA",
    billing_address: "Adresse de Facturation",
    delivery_address: "Adresse de Livraison",
    contact_email: "Email de Facturation",
    phone_number: "Téléphone de la Société",
    contact_person: "Personne de Contact (Responsable)",
    contact_person_name: "Nom",
    position: "Poste",
    contact_person_email: "Email Direct",
    contact_person_phone: "Téléphone Direct",
    save_continue: "Enregistrer et Continuer",
    car_profile: "Profil Véhicule",
    car_desc: "Ajoutez un nouveau véhicule à votre flotte.",
    back: "Retour",
    vehicle_specs: "Spécifications du Véhicule",
    brand: "Marque",
    model: "Modèle",
    engine_model: "Modèle Moteur",
    transmission: "Transmission",
    brakes_type: "Type de Freins",
    required_photos: "Photos Requises",
    photos_desc: "Veuillez télécharger des photos claires pour vérification.",
    conn_front: "Vue Avant Connecteur",
    lever_side: "Vue Latérale Levier",
    ecu_part: "Réf. Pièce ECU",
    ecu_front: "Vue Avant ECU",
    extra_photo: "Photo Supplémentaire",
    tech_docs: "Documents Techniques",
    elec_scheme: "Schéma Électrique",
    elec_desc: "Téléchargez le PDF ou l'image du schéma électrique",
    sensors_list: "Liste Capteurs",
    sensors_desc: "Téléchargez la liste des capteurs et actionneurs",
    cancel: "Annuler",
    save_car: "Enregistrer Véhicule",
    your_vehicles: "Vos Véhicules",
    add_vehicle: "Ajouter Véhicule",
    no_vehicles: "Aucun véhicule ajouté",
    no_vehicles_desc: "Créez un profil pour chaque voiture afin de gérer les configurations et documents.",
    add_first_car: "Ajouter Votre Première Voiture",
    configure_videos: "Configurer Vidéos",
    demo_url: "URL Vidéo Démo",
    setup_url: "URL Vidéo Configuration",
    save_changes: "Enregistrer Changements",
    upload_click: "Cliquer pour télécharger",
    uploading: "Téléchargement...",
    file_uploaded: "Fichier téléchargé",
    view_file: "Voir fichier",
    delete_car_confirmation: "Êtes-vous sûr de vouloir supprimer ce profil de véhicule ?",
    docs: "Documents",
    photos: "Photos",
    logout: "Déconnexion",
    download_zip: "Télécharger ZIP",
    preparing_zip: "Préparation ZIP...",
    zip_ready: "ZIP Téléchargé",
    download_error: "Échec du téléchargement"
    },
    "pt-br": {
    nav_title: "Soluções KG",
    onboarding_title: "Integração de Clientes",
    onboarding_desc: "Complete seu perfil e configure sua frota.",
    connected: "Conectado",
    export_report: "Exportar Relatório",
    tab_welcome: "Bem-vindo",
    tab_company: "Empresa",
    tab_fleet: "Frota",
    platform_overview: "Visão Geral da Plataforma",
    platform_desc: "Veja como nossa solução se integra ao seu fluxo de trabalho.",
    install_setup: "Instalação e Configuração",
    install_desc: "Guia passo a passo para instalar o conector.",
    get_started: "Começar",
    company_info: "Informações da Empresa",
    company_desc: "Por favor, forneça os detalhes da sua empresa para faturamento.",
    company_name: "Nome da Empresa",
    tax_id: "CNPJ / ID Fiscal",
    billing_address: "Endereço de Cobrança",
    delivery_address: "Endereço de Entrega",
    contact_email: "Email de Cobrança",
    phone_number: "Telefone da Empresa",
    contact_person: "Pessoa de Contato (Responsável)",
    contact_person_name: "Nome",
    position: "Cargo",
    contact_person_email: "Email Direto",
    contact_person_phone: "Telefone Direto",
    save_continue: "Salvar e Continuar",
    car_profile: "Perfil do Veículo",
    car_desc: "Adicione um novo veículo à sua frota.",
    back: "Voltar",
    vehicle_specs: "Especificações do Veículo",
    brand: "Marca",
    model: "Modelo",
    engine_model: "Modelo do Motor",
    transmission: "Transmissão",
    brakes_type: "Tipo de Freios",
    required_photos: "Fotos Necessárias",
    photos_desc: "Por favor, envie fotos claras para verificação.",
    conn_front: "Vista Frontal do Conector",
    lever_side: "Vista Lateral da Alavanca",
    ecu_part: "Número da Peça ECU",
    ecu_front: "Vista Frontal da ECU",
    extra_photo: "Foto Adicional",
    tech_docs: "Documentos Técnicos",
    elec_scheme: "Esquema Elétrico",
    elec_desc: "Envie PDF ou Imagem do esquema elétrico",
    sensors_list: "Lista de Sensores",
    sensors_desc: "Envie lista de sensores e atuadores",
    cancel: "Cancelar",
    save_car: "Salvar Veículo",
    your_vehicles: "Seus Veículos",
    add_vehicle: "Adicionar Veículo",
    no_vehicles: "Nenhum veículo adicionado",
    no_vehicles_desc: "Crie um perfil para cada carro para gerenciar configurações e documentos.",
    add_first_car: "Adicionar Seu Primeiro Carro",
    configure_videos: "Configurar Vídeos",
    demo_url: "URL Vídeo Demo",
    setup_url: "URL Vídeo Configuração",
    save_changes: "Salvar Alterações",
    upload_click: "Clique para enviar",
    uploading: "Enviando...",
    file_uploaded: "Arquivo enviado",
    view_file: "Ver arquivo",
    delete_car_confirmation: "Tem certeza que deseja excluir este perfil de veículo?",
    docs: "Documentos",
    photos: "Fotos",
    logout: "Sair",
    download_zip: "Baixar ZIP",
    preparing_zip: "Preparando ZIP...",
    zip_ready: "ZIP Baixado",
    download_error: "Falha no Download"
    }
    };

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('language');
    if (savedLang && translations[savedLang]) {
      setLanguage(savedLang);
    }
  }, []);

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);